[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"
default_command = "./target/release/polkadot"

[[relaychain.nodes]]
name = "alice"

[[parachains]]
id = 2001
#cumulus_based = true
add_to_genesis = false

[parachains.collator]
name = "collator01"
command = "./target/release/adder-collator"

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
